#!/usr/bin/env sh
export SNIP_PATH=$(dirname `readlink -f $0`)

export NODE_PATH=\
$NODE_PATH\
:$SNIP_PATH\
:$SNIP_PATH/deps/redis-node-client/lib\
:$SNIP_PATH/deps/nerve/lib\
:$SNIP_PATH/deps/ #underscore.js

node "$@"
